services:
  - docker

jobs:
  include:
    - stage: build and push docker image
      script:
      - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
      - docker build --rm -t $DOCKER_USERNAME/hello-app:${TRAVIS_BUILD_ID} .
      - docker images
      - docker push $DOCKER_USERNAME/hello-app:${TRAVIS_BUILD_ID}